# -- Override the chart name used for all resources
nameOverride: ""

# -- Overwrite the fullname of all resources
fullnameOverride: ""

# -- Overwrite the namespace of all resources
namespaceOverride: ""

image:
  # -- (string) Image registry
  registry: ghcr.io
  # -- (string) Image repository
  repository: kyverno/policy-reporter
  # -- (string) Image pullPolicy
  pullPolicy: IfNotPresent
  # -- (string) Image tag
  tag: 3.0.0-rc.4

# -- Deployment replica count
replicaCount: 3

# -- Container port
port:
  name: http
  number: 8080

service:
  # -- Create Service
  enabled: true
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8080
  # -- Service annotations
  annotations: {}
  # -- Service labels
  labels: {}

ingress:
  # -- Create Ingress
  # This ingress exposes the policy-reporter core app.
  enabled: true
  # -- Ingress className
  className: "alb"
  # -- Labels for the Ingress
  labels: {}
  # -- Annotations for the Ingress
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: "default-group"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/group.order: "150"
    alb.ingress.kubernetes.io/certificate-arn: ${cert_arn}
    external-dns.alpha.kubernetes.io/hostname: ${policy_reporter_release_name}.${domain}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host list
  hosts:
   - host: ${policy_reporter_release_name}.${domain}
     paths:
       - path: "/"
         pathType: Prefix
ui:
  # -- (bool) Enable Policy Reporter UI
  enabled: true
  image:
    # -- (string) Image registry
    registry: ghcr.io
    # -- (string) Image repository
    repository: kyverno/policy-reporter-ui
    # -- (string) Image PullPolicy
    pullPolicy: IfNotPresent
    # -- (string) Image tag
    tag: "2.0.0-rc.3"

  # -- Deployment replica count
  replicaCount: 1

  # -- Temporary Directory to persist session data for authentication
  tempDir: "/tmp"

plugin:
  kyverno:
    # -- (bool) Enable Kyverno Plugin
    enabled: true
    image:
      # -- (string) Image registry
      registry: ghcr.io
      # -- (string) Image repository
      repository: kyverno/policy-reporter/kyverno-plugin
      # -- (string) Image PullPolicy
      pullPolicy: IfNotPresent
      # -- (string) Image tag
      tag: "0.4.0"

    # -- Deployment replica count
    replicaCount: 2
