repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--config=config.flake8']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_tflint
        args:
          - --args=--fix
      - id: terraform_tfsec
        args:
          - --args=--minimum-severity CRITICAL
          - --args=--force-all-dirs
exclude: ^templates/aws/airflow/ # single directory recursive
# exclude: ^(templates/aws/airflow|iac|automation)/ # multiple directories recursive (templates/aws/airflow, iac, automation)
 
#  The  exclude  key is used to exclude certain directories from the pre-commit checks. 
#  The  repos  key is a list of repositories that contain the hooks that will be run. Each repository has a  hooks  key that contains a list of hooks that will be run. 
#  The  id  key is the name of the hook that will be run. The  args  key is a list of arguments that will be passed to the hook. 
#  The  language_version  key is used to specify the version of the language that the hook should be run with. 
#  The  rev  key is used to specify the version of the repository that should be used
