ci:
  autoupdate_schedule: quarterly
  skip:
  - shfmt
  - shellcheck
  - hadolint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--config=config.flake8']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_tflint
        args:
          - --args=--fix
      - id: terraform_tfsec
        args:
          - --args=--minimum-severity CRITICAL
          - --args=--force-all-dirs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Non-modifying checks:
    - id: name-tests-test
      files: >-
        ^tests/[^_].*\.py$

    # Security
    - id: detect-aws-credentials
      args:
      - --allow-missing-credentials
    - id: detect-private-key

    # Detect hardcoded secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.3
    hooks:
    - id: gitleaks

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
    - id: yamllint
      types:
      - file
      - yaml
      args:
      - --strict

  # JSON5 Linter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    - id: prettier
      # https://prettier.io/docs/en/options.html#parser
      files: .json5$

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.15.0
    hooks:
    - id: mypy
      alias: mypy-py313
      name: MyPy, for Python 3.13
      additional_dependencies:
      - lxml  # dep of `--txt-report`, `--cobertura-xml-report` & `--html-report`
      - pytest
      - pytest-mock
      - pytest-xdist

      args:
      - --python-version=3.13
      - --any-exprs-report=.tox/.tmp/.test-results/mypy--py-3.13
      - --cobertura-xml-report=.tox/.tmp/.test-results/mypy--py-3.13
      - --html-report=.tox/.tmp/.test-results/mypy--py-3.13
      - --linecount-report=.tox/.tmp/.test-results/mypy--py-3.13
      - --linecoverage-report=.tox/.tmp/.test-results/mypy--py-3.13
      - --lineprecision-report=.tox/.tmp/.test-results/mypy--py-3.13
      - --txt-report=.tox/.tmp/.test-results/mypy--py-3.13
      pass_filenames: false
    - id: mypy
      alias: mypy-py311
      name: MyPy, for Python 3.11
      additional_dependencies:
      - lxml  # dep of `--txt-report`, `--cobertura-xml-report` & `--html-report`
      - pytest
      - pytest-mock
      args:
      - --python-version=3.11
      - --any-exprs-report=.tox/.tmp/.test-results/mypy--py-3.11
      - --cobertura-xml-report=.tox/.tmp/.test-results/mypy--py-3.11
      - --html-report=.tox/.tmp/.test-results/mypy--py-3.11
      - --linecount-report=.tox/.tmp/.test-results/mypy--py-3.11
      - --linecoverage-report=.tox/.tmp/.test-results/mypy--py-3.11
      - --lineprecision-report=.tox/.tmp/.test-results/mypy--py-3.11
      - --txt-report=.tox/.tmp/.test-results/mypy--py-3.11
      pass_filenames: false
    - id: mypy
      alias: mypy-py39
      name: MyPy, for Python 3.9
      additional_dependencies:
      - lxml  # dep of `--txt-report`, `--cobertura-xml-report` & `--html-report`
      - pytest
      - pytest-mock
      args:
      - --python-version=3.9
      - --any-exprs-report=.tox/.tmp/.test-results/mypy--py-3.9
      - --cobertura-xml-report=.tox/.tmp/.test-results/mypy--py-3.9
      - --html-report=.tox/.tmp/.test-results/mypy--py-3.9
      - --linecount-report=.tox/.tmp/.test-results/mypy--py-3.9
      - --linecoverage-report=.tox/.tmp/.test-results/mypy--py-3.9
      - --lineprecision-report=.tox/.tmp/.test-results/mypy--py-3.9
      - --txt-report=.tox/.tmp/.test-results/mypy--py-3.9
      pass_filenames: false

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    - id: shfmt
      args:
      - -l
      - -i
      - '2'
      - -ci
      - -sr
      - -w
    - id: shellcheck

  # Dockerfile linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
    - id: hadolint
      args:
      - --ignore=DL3007  # Using latest
      - --ignore=DL3013  # Pin versions in pip
      - --ignore=DL3027  # Do not use apt
      - --ignore=DL3059  # Docker `RUN`s shouldn't be consolidated here
      - --ignore=DL4006  # Not related to alpine
      - --ignore=SC1091  # Useless check
      - --ignore=SC2015  # Useless check
      - --ignore=SC3037  # Not related to alpine
# exclude: ^templates/aws/airflow/ # single directory recursive
# multiple directories recursive (templates/aws/airflow, iac, automation)
exclude: ^(templates/aws/airflow/|templates/aws/charts/engines/apache_airflow_merckk/)
