apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-psa-labels
spec:
  rules:
  - name: add-psa-labels
    match:
      resources:
        kinds:
        - Namespace
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            pod-security.kubernetes.io/enforce: "baseline"
            pod-security.kubernetes.io/warn: "restricted"
