name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js (for Prettier)
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # You can specify the version of Node.js you need

    - name: Lint
      run: |
        make lint
