name: ∞

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  merge_group:
  workflow_call:  # a way to embed the main tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: |
        make lint
