name: Push code into S3 bucket

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  DEPLOY_ACCOUNT: ${{ vars.DEPLOY_ACCOUNT }}
  PROVISIONER_REGION: ${{ vars.PROVISIONER_REGION }}
  DEPLOYMENT_ROLE_NAME: ${{ vars.DEPLOYMENT_ROLE_NAME }}
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set archive file name and S3 upload path
        run: |
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            export ARCHIVE_FILE_NAME="${{ github.event.repository.name }}-main.zip"
            export S3_UPLOAD_PATH="branches/${{ github.event.repository.name }}/main.zip"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            export TAG_NAME="${{ github.ref_name }}"
            export ARCHIVE_FILE_NAME="${{ github.event.repository.name }}-${TAG_NAME}.zip"
            export S3_UPLOAD_PATH="tags/${{ github.event.repository.name }}/${TAG_NAME}.zip"
          fi
          echo "ARCHIVE_FILE_NAME=$ARCHIVE_FILE_NAME" >> $GITHUB_ENV
          echo "S3_UPLOAD_PATH=$S3_UPLOAD_PATH" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.DEPLOY_ACCOUNT }}:role/${{ env.DEPLOYMENT_ROLE_NAME }}
          aws-region: ${{ env.PROVISIONER_REGION }}

      - name: Create and Upload Archive to S3
        run: |
          git archive --format=zip --output=${{ env.ARCHIVE_FILE_NAME }} ${{ github.ref }}
          aws s3 cp ${{ env.ARCHIVE_FILE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_UPLOAD_PATH }} --region ${{ env.PROVISIONER_REGION }}
